name: SpawnIslandRTP
version: $version
author: Strokkur24
api-version: 1.21.5

main: net.strokkur.spawnislandrtp.SpawnIslandRTPPlugin
load: POSTWORLD

permissions:
  spawnislandrtp.command:
    description: Permission for /spawnislandrtp
    default: op
    
dependencies:
  server:
    BetterRTP:
      load: BEFORE
      required: true
      join-classpath: true